In [1]:
import pandas as pd 
import numpy as np
import pickle
import os 
from sklearn.preprocessing import LabelEncoder

DATA_DIR = "../data"
RAW_DIR = f"{DATA_DIR}/raw"
PROCESSED_DIR = f"{DATA_DIR}/processed"
os.makedirs(f"{PROCESSED_DIR}/encoders", exist_ok=True)

In [3]:
# Read raw data
df = pd.read_csv(f"{RAW_DIR}/Dataset.csv")

print("shape of raw data: ", df.shape) 
df.head(10)

shape of raw data:  (447915, 76)

,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,214392,9,21,388.0,24564.0,194.0,0.0,43.111111,85.545959,1460.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2376792,9,3,752.0,0.0,188.0,0.0,83.555556,99.084700,0.0,...,4,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,131350,10,3,7564.0,0.0,1460.0,0.0,756.400000,690.497277,0.0,...,6,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,164796,6,3,770.0,0.0,385.0,0.0,128.333333,198.813145,0.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,163418,6,3,400.0,0.0,200.0,0.0,66.666667,103.279556,0.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,235721,7,5,360.0,600.0,180.0,0.0,51.428571,87.831007,300.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2570808,9,3,1472.0,0.0,368.0,0.0,163.555556,193.953030,0.0,...,4,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,414846,7,7,394.0,552.0,197.0,0.0,56.285714,96.126157,276.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,184968,7,7,384.0,3576.0,192.0,0.0,54.857143,93.686407,1460.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,182141,7,11,432.0,8858.0,216.0,0.0,61.714286,105.397208,1460.0,...,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
desc = df.describe()
print(f"total features : {len(df.columns)}" )
print(f"All numerical : {all(df.dtypes != 'object')}" )
print(f"Rows {len(df)}")
print()

print("Feature ranges :")

desc.loc[['min', 'max', 'mean', 'std']].head(10)

total features : 76
All numerical : True
Rows 447915

Feature ranges :

,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
min,1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,8.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.199975e+08,20038.000000,11021.000000,2.605270e+07,1.421599e+07,1476.000000,1472.000000,1474.000000,848.528137,1460.000000,...,20032.000000,40.000000,1.104063e+08,7.417760e+07,1.104063e+08,1.104063e+08,1.191926e+08,7.214360e+07,1.191926e+08,1.191926e+08
mean,5.983003e+05,22.598428,27.238503,4.778406e+03,2.170251e+04,174.243153,14.918360,71.264324,64.000867,365.009993,...,8.628521,25.926651,1.868487e+04,9.409518e+03,3.126578e+04,1.252120e+04,9.859284e+04,3.341817e+03,1.026228e+05,9.578854e+04
std,4.878777e+06,127.986936,116.638803,1.518561e+05,1.477431e+05,352.171446,71.570572,184.565303,156.387353,555.808533,...,118.663262,9.017636,7.487275e+05,5.231382e+05,1.174788e+06,6.397847e+05,2.222806e+06,2.201782e+05,2.260988e+06,2.207332e+06